<div style="padding:5px; border-radius:10px;background-color:lightsalmon;">
<h1 style="text-align:center;color:black;"> Traitement de données en table : Les séries TV </h1>
<h3 style="text-align:center;"> Première NSI</h3>

<h4 style="text-align:center;"> MB </h4>


</div>

Nous allons utiliser la bibliothèque **Pandas** de python pour faire des calculs sur les tables de données. Pour cela il va falloir commencer par importer la bibliothèque en utilisant l'alias pd.  
**Toutes les cellules où il est marqué #TODO comporte un travail à faire. Utiliser le cours disponibe sur pearltrees si besoin**

In [28]:
# importation de la bibliothèque en utilisant l'alias pd
import pandas as pd

<h2 style="color: orange; font-style: 16px italic verdana;">  Importer un fichier csv</h2>

Un fichier .csv est en fait un tableau de données. Ce tableau va être importer dans python grâce à un module de la bibliothèque **Pandas**.
La commande `read_csv(nom du fichier;separateur;encodage)`

In [71]:
series = pd.read_csv("tv_shows.csv",sep=";",encoding='utf8')

`series` est un objet bien pariculier de python appelé **DataFrame**. 
La commande `series.head()` permet d'afficher les 5 premières lignes.  
 <div class="alert alert-success" style="border-left: 5px solid #3c763d;border-radius:2px;">
Afficher le type de `series` et les 5 premieres lignes du tableau.</div>

In [72]:
print(type(series))
series.head()

<class 'pandas.core.frame.DataFrame'>

,ID,Title,Year,Age,note,RottenTomatoes,Netflix,Hulu,PrimeVideo,Disney+
0,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0
1,2,Stranger Things,2016.0,16+,"8,7",96,1,0,0.0,0.0
2,3,Attack on Titan,2013.0,18+,9,95,1,1,0.0,0.0
3,4,Better Call Saul,2015.0,18+,"8,8",94,1,0,0.0,0.0
4,5,Dark,2017.0,16+,"8,8",93,1,0,0.0,0.0

<h2 style="color: orange; font-style: 16px italic verdana;"> Les fonctions d'affichage</h2>

On vient de voir `head()`qui permet d'afficher le début du tableau pour vérifier en choissant en argument le nombre de lignes (5 par défault).

`tail()`fait la même chose mais avec la fin du tableau.

 <div class="alert alert-success" style="border-left: 5px solid #3c763d;border-radius:2px;">Afficher les 15 dernières lignes du tableau. </div>

In [31]:
series.shape

(5368, 10)

In [32]:
series.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5368 entries, 0 to 5367
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              5368 non-null   int64
 1   Title           5368 non-null   object
 2   Year            5357 non-null   float64
 3   Age             3207 non-null   object
 4   note            5366 non-null   object
 5   RottenTomatoes  5368 non-null   int64
 6   Netflix         5368 non-null   int64
 7   Hulu            5368 non-null   int64
 8   PrimeVideo      5367 non-null   float64
 9   Disney+         5331 non-null   float64
dtypes: float64(3), int64(4), object(3)
memory usage: 419.5+ KB

In [33]:
series.tail()

,ID,Title,Year,Age,note,RottenTomatoes,Netflix,Hulu,PrimeVideo,Disney+
5363,4903,Miracle of Faith: 2000 Years of Christianity i...,2000.0,NaN,#VALEUR!,16,0,0,1.0,0.0
5364,1342,Schulz Saves America: Pandemics Predators Pr...,NaN,NaN,"7,5",46,1,0,0.0,0.0
5365,1514,Rica Famosa Latina,NaN,NaN,"5,7",42,1,1,0.0,0.0
5366,2311,McCartney 3212,NaN,NaN,9,68,0,1,0.0,0.0
5367,4804,Sesame Street: 321 Lets Go,NaN,NaN,2,21,0,0,1.0,0.0

Que font les fonctions `shape`  et `ìnfo()` ?  
`shape` : donne le nombre de lignes et le nombre de colonnes  
`ìnfo()` : donne des informations sur les types de données (nb de données non renseignées, descripteur, type)

 <div class="alert alert-success" style="border-left: 5px solid #3c763d;border-radius:2px;">Executer le code ci-dessous. Que fait-il?
</div>

affiche tous et que les valeurs de l'attribut 'Title'

In [34]:
series['Title']

0                                 History of Westinghouse
1                             The Little Rascals Classics
2                                              Betty Boop
3                                       The Three Stooges
4                                               Noveltoon
                              ...
5363    Miracle of Faith: 2000 Years of Christianity i...
5364    Schulz Saves America: Pandemics  Predators  Pr...
5365                                 Rica  Famosa  Latina
5366                                       McCartney 3212
5367                           Sesame Street: 321 Lets Go
Name: Title, Length: 5368, dtype: object

 <div class="alert alert-success" style="border-left: 5px solid #3c763d;border-radius:2px;">Afficher uniquement les  premiers titres (utiliser le slice comme pour les listes)</div>

In [35]:
series['Title'][:5]

0        History of Westinghouse
1    The Little Rascals Classics
2                     Betty Boop
3              The Three Stooges
4                      Noveltoon
Name: Title, dtype: object

In [36]:
#Tester ceci
series[['Title','Year']]

                                                  Title    Year
0                               History of Westinghouse  1904.0
1                           The Little Rascals Classics  1931.0
2                                            Betty Boop  1932.0
3                                     The Three Stooges  1934.0
4                                             Noveltoon  1943.0
...                                                 ...     ...
5363  Miracle of Faith: 2000 Years of Christianity i...  2000.0
5364  Schulz Saves America: Pandemics  Predators  Pr...     NaN
5365                               Rica  Famosa  Latina     NaN
5366                                     McCartney 3212     NaN
5367                         Sesame Street: 321 Lets Go     NaN

[5368 rows x 2 columns]

<h2 style="color: orange; font-style: 16px italic verdana;">  Trier les données</h2>

In [16]:
#Trier par ordre croissant ou décroissant : 
series.sort_values(by='Title',ascending=True)[0:15]

,ID,Title,Year,Age,note,RottenTomatoes,Netflix,Hulu,PrimeVideo,Disney+
4461,4763,#MeToo,Now What?,2018,#VALEUR!,27,0,0,1.0,NaN
3368,3501,#ThatsHarassment,2018,NaN,#VALEUR!,14,0,1,1.0,0.0
891,894,#blackAF,2020,18+,"6,8",54,1,0,0.0,0.0
854,857,(The Hook Up Plan),2018,16+,"7,2",55,1,0,0.0,0.0
1111,1114,(Un)Well,2020,18+,"6,4",50,1,0,0.0,0.0
2973,3098,.hack,2002,7+,"6,9",45,0,1,0.0,0.0
2042,2074,09/01/2001,2018,16+,"7,8",79,0,1,0.0,0.0
3347,3480,10 Essentials,2013,NaN,#VALEUR!,16,0,1,1.0,0.0
2266,2323,10 Things I Hate About You,2009,16+,"7,3",67,0,1,0.0,1.0
3858,4124,10.5: Apocalypse,2006,NaN,"4,5",48,0,0,1.0,0.0
829,832,100 Days My Prince,2018,16+,"7,7",55,1,0,0.0,0.0
1073,1076,100 Humans. Lifes Questions. Answered.,2020,NaN,"5,7",51,1,0,0.0,0.0
3965,4243,100 Years of Horror,1996,NaN,"7,2",45,0,0,1.0,0.0
1302,1305,100% Hotter,2016,NaN,"4,4",46,1,0,0.0,0.0
5260,5605,101 Dalmatian Street,2019,7+,"6,3",44,0,0,0.0,1.0

 <div class="alert alert-success" style="border-left: 5px solid #3c763d;border-radius:2px;">Expliquer les arguments de la fonction.  </div>

ascending signifie ascendant (ordre croissant). On trie dans l'ordre croissant de l'attribut 'Title'

<div class="alert alert-success" style="border-left: 5px solid #3c763d;border-radius:2px;">Afficher la liste des 10 séries les plus récentes. </div>

In [37]:
series.sort_values(by='Year',ascending=False)[0:10]

,ID,Title,Year,Age,note,RottenTomatoes,Netflix,Hulu,PrimeVideo,Disney+
5108,601,Fatma,2021.0,NaN,"7,5",61,1,0,0.0,0.0
5165,1015,Power Rangers Dino Fury,2021.0,7+,"6,8",52,1,0,0.0,0.0
5159,946,The Rational Life,2021.0,NaN,"8,2",53,1,0,0.0,0.0
5160,953,Spycraft,2021.0,18+,"6,7",53,1,0,0.0,0.0
5161,955,Headspace Guide to Meditation,2021.0,7+,"8,5",53,1,0,0.0,0.0
5162,966,You Are My Spring,2021.0,NaN,"7,3",53,1,0,0.0,0.0
5163,974,Jiva!,2021.0,18+,"5,7",53,1,0,0.0,0.0
5164,981,Country Comfort,2021.0,7+,"6,9",52,1,0,0.0,0.0
5166,1019,We the People,2021.0,7+,"4,5",52,1,0,0.0,0.0
5209,1587,Lets Fight Ghost,2021.0,NaN,"7,7",40,1,0,0.0,0.0

In [38]:
#Selection des séries de 2018
series18=series['Title'][series['Year']==2018]
#on affiche le sous-dataframe
print(series18)

3544                                Cobra Kai
3545                                    Elite
3546                                      YOU
3547                               Good Girls
3548                                     Pose
                        ...
4099    Fearless Adventures with Jack Randall
5331                Kokkoku  Moment by Moment
5333              Montréal: My Love  My Story
5338                        #MeToo  Now What?
5360                         I Draw  You Cook
Name: Title, Length: 560, dtype: object

<div class="alert alert-success" style="border-left: 5px solid #3c763d;border-radius:2px;">Afficher la liste des séries des années 1995 à 1999 inclues. Pour ajouter deux conditions on peut remplacer la condition vue précédememnt par <code>(condition 1)&(condition2)</code></div>

In [39]:
series9599=series[['Title','Year']][(series['Year']>=1995) & (series['Year']<=1999)]
print(series9599)

                                                 Title    Year
282                            Neon Genesis Evangelion  1995.0
283                                 Star Trek: Voyager  1995.0
284                                         Goosebumps  1995.0
285                                Pride and Prejudice  1995.0
286                                            Sliders  1995.0
...                                                ...     ...
410                               Spider-Man Unlimited  1999.0
411                    The Avengers: United They Stand  1999.0
5297  I  Caesar: The Rise and Fall of the Roman Empire  1997.0
5305                         Pinky  Elmyra & the Brain  1998.0
5353                        Sabrina  the Teenage Witch  1996.0

[133 rows x 2 columns]

<h2 style="color: orange; font-style: 16px italic verdana;"> Fusionner les tables</h2>

<div class="alert alert-success" style="border-left: 5px solid #3c763d;border-radius:2px;">Ecrire le code pour ouvrir la 2eme table nommée "users_tv.csv" et créer le dataframe <code>users</code>.</div>

In [40]:
users= pd.read_csv("users_tv.csv",sep=";",encoding='utf8')
users

,Nom,email,age,Netflix,Prime,Hulu,Disney+
0,Todd Bates,mollis.lectus.pede@outlook.edu,5,0,0,1,0
1,Mohammad Riggs,nullam@aol.couk,5,1,1,0,1
2,Marvin Blackwell,velit.sed@protonmail.couk,6,1,1,0,0
3,Christopher Wade,sem.egestas@icloud.org,6,1,0,1,0
4,Chloe Snyder,pellentesque@protonmail.couk,3,0,0,0,1
...,...,...,...,...,...,...,...
124,Raphael Greer,sit@outlook.couk,39,0,1,0,1
125,Kameko Mccormick,ante.maecenas@aol.ca,37,1,0,1,0
126,Courtney Nelson,malesuada.id@yahoo.com,32,1,0,1,0
127,Mira Michael,nisi.cum@outlook.edu,35,1,0,1,1
128,Jeremy Fulton,quisque@hotmail.com,36,1,0,0,1

La fonction `merge` est une jointure (vous verrez cela en cours de Base de Données à l'automne prochain). Elle permet de créer un nouveau dataframe qui en mélange deux.

le nouveau dataframe a l'ensemble des colonnes des deux dataframe.
   pour les lignes, il combine les lignes des deux dataframes d'entrée qui ont des valeurs identiques pour certaines colonnes. Ces colonnes sont données par `left_on` et `right_on`.  
    
   
   <div class="alert alert-success" style="border-left: 5px solid #3c763d;border-radius:2px;">Afficher les 5 premieres lignes.</div>

In [42]:
DF = series.merge(users, left_on="Netflix", right_on="Netflix")
DF[:5]

,ID,Title,Year,Age,note,RottenTomatoes,Netflix,Hulu_x,PrimeVideo,Disney+_x,Nom,email,age,Prime,Hulu_y,Disney+_y
0,4850,History of Westinghouse,1904.0,NaN,#VALEUR!,17,0,0,1.0,0.0,Todd Bates,mollis.lectus.pede@outlook.edu,5,0,1,0
1,4850,History of Westinghouse,1904.0,NaN,#VALEUR!,17,0,0,1.0,0.0,Chloe Snyder,pellentesque@protonmail.couk,3,0,0,1
2,4850,History of Westinghouse,1904.0,NaN,#VALEUR!,17,0,0,1.0,0.0,Jade Pope,dictum.placerat@google.net,7,1,1,0
3,4850,History of Westinghouse,1904.0,NaN,#VALEUR!,17,0,0,1.0,0.0,Ishmael Merrill,arcu.aliquam@hotmail.ca,4,1,1,0
4,4850,History of Westinghouse,1904.0,NaN,#VALEUR!,17,0,0,1.0,0.0,Yoshi Bradley,etiam.laoreet@aol.ca,15,0,1,1

Cela nous permet de savoir par série quelles sont les personnes qui peuvent la regarder sur netflix.

<div class="alert alert-success" style="border-left: 5px solid #3c763d;border-radius:2px;">Afficher les noms des 3 personnes les plus agées.</div>

In [46]:
users.sort_values(by='age', ascending=False)[['Nom','age']][0:3]

                 Nom  age
100     Caleb Osborn   85
96   Burton Harrison   84
93          Ali Reed   81

<h2 style="color: orange; font-style: 16px italic verdana;"> Calculs statistiques</h2>

<div class="alert alert-success" style="border-left: 5px solid #3c763d;border-radius:2px;">Créer un sous-dataframe pour  lister les noms et prénoms des utilisateurs qui peuvent regarder Breaking Bad (netflix).</div>

In [48]:
BB=DF[DF['Title']=='Breaking Bad']
BB

,ID,Title,Year,Age,note,RottenTomatoes,Netflix,Hulu_x,PrimeVideo,Disney+_x,Nom,email,age,Prime,Hulu_y,Disney+_y
244291,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Mohammad Riggs,nullam@aol.couk,5,1,0,1
244292,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Marvin Blackwell,velit.sed@protonmail.couk,6,1,0,0
244293,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Christopher Wade,sem.egestas@icloud.org,6,0,1,0
244294,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Wynter Nelson,tellus.sem@protonmail.edu,5,0,0,1
244295,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Uta Moses,nullam.feugiat@yahoo.edu,3,1,0,1
244296,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Violet Farrell,donec.fringilla.donec@google.com,11,0,1,0
244297,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Aurora Finch,aliquam.adipiscing@google.edu,17,0,1,1
244298,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Alvin Pitts,montes@google.edu,14,0,0,1
244299,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Rhea Stanton,aliquam.adipiscing@protonmail.ca,12,0,1,1
244300,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Dustin Shepard,auctor.velit.aliquam@yahoo.couk,17,1,0,1
244301,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Sylvester Rosa,facilisis.facilisis@outlook.ca,20,1,1,1
244302,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Renee Pierce,proin.sed@hotmail.org,14,0,1,0
244303,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Sybill Benson,quis.tristique.ac@protonmail.com,17,1,0,1
244304,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Brock Caldwell,quis.lectus@hotmail.ca,12,1,0,1
244305,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Violet Farrell,donec.fringilla.donec@google.com,27,0,1,0
244306,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Aurora Finch,aliquam.adipiscing@google.edu,27,0,1,1
244307,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Alvin Pitts,montes@google.edu,21,0,0,1
244308,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Rhea Stanton,aliquam.adipiscing@protonmail.ca,25,0,1,1
244309,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Dustin Shepard,auctor.velit.aliquam@yahoo.couk,28,1,0,1
244310,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Sylvester Rosa,facilisis.facilisis@outlook.ca,22,1,1,1
244311,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Renee Pierce,proin.sed@hotmail.org,31,0,1,0
244312,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Sybill Benson,quis.tristique.ac@protonmail.com,38,1,0,1
244313,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Brock Caldwell,quis.lectus@hotmail.ca,18,1,0,1
244314,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Raja Guerrero,neque.sed@outlook.edu,37,1,1,1
244315,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Gay Keith,orci.ut.sagittis@protonmail.edu,51,1,0,1
244316,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Madonna Riley,aliquam.erat@hotmail.ca,46,1,1,0
244317,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Rinah Mayo,ante@protonmail.net,42,0,1,0
244318,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Ciaran Foreman,nec@outlook.edu,47,1,0,1
244319,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Mary Barron,libero.integer@outlook.net,44,0,0,1
244320,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Zachary Holland,sit@google.net,47,1,0,0
244321,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Josephine Mcneil,nec.euismod@google.ca,48,1,1,1
244322,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Lisandra Nolan,risus.donec@google.org,43,1,0,0
244323,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Darryl Warner,non.feugiat@icloud.com,45,0,1,0
244324,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Jeremy Gates,aliquet.magna.a@hotmail.com,59,0,0,1
244325,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Prescott Pena,sem.elit@protonmail.net,55,1,0,0
244326,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Deborah Mcclure,fusce.fermentum@icloud.ca,53,0,0,1
244327,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Gwendolyn Huber,consequat@hotmail.net,60,0,0,0
244328,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Leonard Dickson,ac@protonmail.couk,68,0,0,0
244329,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Mechelle Haynes,penatibus.et@aol.couk,72,0,0,0
244330,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Clinton Hopkins,egestas.fusce@icloud.couk,51,1,1,1
244331,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Christen Rosario,luctus@aol.com,53,1,1,1
244332,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Lamar Stein,ac.facilisis.facilisis@protonmail.couk,53,0,1,0
244333,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Hoyt Dorsey,eu.erat@aol.ca,50,1,1,1
244334,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Ali Reed,fusce.aliquet@google.ca,81,0,1,0
244335,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,India Richmond,purus@google.edu,59,0,0,0
244336,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Bell Haney,tempus@yahoo.com,53,0,0,1
244337,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Kathleen Rasmussen,vitae.erat@aol.org,64,1,0,0
244338,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Garrison Randall,magna.sed.dui@hotmail.ca,57,1,1,1
244339,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Mia Sykes,nascetur.ridiculus@protonmail.com,39,0,1,1
244340,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Kerry Hood,egestas@outlook.org,30,1,1,1
244341,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Gil Ashley,non@yahoo.net,31,0,0,1
244342,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Macy Owens,fermentum@protonmail.com,33,1,0,1
244343,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Leandra Levy,arcu.et@outlook.ca,38,1,1,1
244344,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,MacKenzie Jenkins,convallis.in@protonmail.couk,35,0,1,1
244345,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Lillian James,tortor@protonmail.com,37,0,0,0
244346,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Kameko Mccormick,ante.maecenas@aol.ca,37,0,1,0
244347,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Courtney Nelson,malesuada.id@yahoo.com,32,0,1,0
244348,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Mira Michael,nisi.cum@outlook.edu,35,0,1,1
244349,1,Breaking Bad,2008.0,18+,"9,4",100,1,0,0.0,0.0,Jeremy Fulton,quisque@hotmail.com,36,0,0,1

<div class="alert alert-success" style="border-left: 5px solid #3c763d;border-radius:2px;">Créer un sous-dataframe pour chaque plateforme contenant la liste des personnes abonnées.</div>

In [51]:
netflix=users[users['Netflix']==1]
netflix

,Nom,email,age,Netflix,Prime,Hulu,Disney+
1,Mohammad Riggs,nullam@aol.couk,5,1,1,0,1
2,Marvin Blackwell,velit.sed@protonmail.couk,6,1,1,0,0
3,Christopher Wade,sem.egestas@icloud.org,6,1,0,1,0
5,Wynter Nelson,tellus.sem@protonmail.edu,5,1,0,0,1
7,Uta Moses,nullam.feugiat@yahoo.edu,3,1,1,0,1
10,Violet Farrell,donec.fringilla.donec@google.com,11,1,0,1,0
12,Aurora Finch,aliquam.adipiscing@google.edu,17,1,0,1,1
13,Alvin Pitts,montes@google.edu,14,1,0,0,1
18,Rhea Stanton,aliquam.adipiscing@protonmail.ca,12,1,0,1,1
20,Dustin Shepard,auctor.velit.aliquam@yahoo.couk,17,1,1,0,1
21,Sylvester Rosa,facilisis.facilisis@outlook.ca,20,1,1,1,1
22,Renee Pierce,proin.sed@hotmail.org,14,1,0,1,0
25,Sybill Benson,quis.tristique.ac@protonmail.com,17,1,1,0,1
28,Brock Caldwell,quis.lectus@hotmail.ca,12,1,1,0,1
30,Violet Farrell,donec.fringilla.donec@google.com,27,1,0,1,0
32,Aurora Finch,aliquam.adipiscing@google.edu,27,1,0,1,1
33,Alvin Pitts,montes@google.edu,21,1,0,0,1
38,Rhea Stanton,aliquam.adipiscing@protonmail.ca,25,1,0,1,1
40,Dustin Shepard,auctor.velit.aliquam@yahoo.couk,28,1,1,0,1
41,Sylvester Rosa,facilisis.facilisis@outlook.ca,22,1,1,1,1
42,Renee Pierce,proin.sed@hotmail.org,31,1,0,1,0
45,Sybill Benson,quis.tristique.ac@protonmail.com,38,1,1,0,1
48,Brock Caldwell,quis.lectus@hotmail.ca,18,1,1,0,1
49,Raja Guerrero,neque.sed@outlook.edu,37,1,1,1,1
50,Gay Keith,orci.ut.sagittis@protonmail.edu,51,1,1,0,1
51,Madonna Riley,aliquam.erat@hotmail.ca,46,1,1,1,0
53,Rinah Mayo,ante@protonmail.net,42,1,0,1,0
55,Ciaran Foreman,nec@outlook.edu,47,1,1,0,1
57,Mary Barron,libero.integer@outlook.net,44,1,0,0,1
60,Zachary Holland,sit@google.net,47,1,1,0,0
62,Josephine Mcneil,nec.euismod@google.ca,48,1,1,1,1
63,Lisandra Nolan,risus.donec@google.org,43,1,1,0,0
68,Darryl Warner,non.feugiat@icloud.com,45,1,0,1,0
70,Jeremy Gates,aliquet.magna.a@hotmail.com,59,1,0,0,1
71,Prescott Pena,sem.elit@protonmail.net,55,1,1,0,0
73,Deborah Mcclure,fusce.fermentum@icloud.ca,53,1,0,0,1
77,Gwendolyn Huber,consequat@hotmail.net,60,1,0,0,0
78,Leonard Dickson,ac@protonmail.couk,68,1,0,0,0
83,Mechelle Haynes,penatibus.et@aol.couk,72,1,0,0,0
84,Clinton Hopkins,egestas.fusce@icloud.couk,51,1,1,1,1
85,Christen Rosario,luctus@aol.com,53,1,1,1,1
90,Lamar Stein,ac.facilisis.facilisis@protonmail.couk,53,1,0,1,0
91,Hoyt Dorsey,eu.erat@aol.ca,50,1,1,1,1
93,Ali Reed,fusce.aliquet@google.ca,81,1,0,1,0
94,India Richmond,purus@google.edu,59,1,0,0,0
95,Bell Haney,tempus@yahoo.com,53,1,0,0,1
98,Kathleen Rasmussen,vitae.erat@aol.org,64,1,1,0,0
101,Garrison Randall,magna.sed.dui@hotmail.ca,57,1,1,1,1
110,Mia Sykes,nascetur.ridiculus@protonmail.com,39,1,0,1,1
112,Kerry Hood,egestas@outlook.org,30,1,1,1,1
113,Gil Ashley,non@yahoo.net,31,1,0,0,1
114,Macy Owens,fermentum@protonmail.com,33,1,1,0,1
115,Leandra Levy,arcu.et@outlook.ca,38,1,1,1,1
121,MacKenzie Jenkins,convallis.in@protonmail.couk,35,1,0,1,1
122,Lillian James,tortor@protonmail.com,37,1,0,0,0
125,Kameko Mccormick,ante.maecenas@aol.ca,37,1,0,1,0
126,Courtney Nelson,malesuada.id@yahoo.com,32,1,0,1,0
127,Mira Michael,nisi.cum@outlook.edu,35,1,0,1,1
128,Jeremy Fulton,quisque@hotmail.com,36,1,0,0,1

In [61]:
prime=users[users['Prime']==1]
prime

,Nom,email,age,Netflix,Prime,Hulu,Disney+
1,Mohammad Riggs,nullam@aol.couk,5,1,1,0,1
2,Marvin Blackwell,velit.sed@protonmail.couk,6,1,1,0,0
6,Jade Pope,dictum.placerat@google.net,7,0,1,1,0
7,Uta Moses,nullam.feugiat@yahoo.edu,3,1,1,0,1
8,Ishmael Merrill,arcu.aliquam@hotmail.ca,4,0,1,1,0
11,Zenia Farmer,lacus.aliquam@aol.com,12,0,1,0,1
16,Chaney Herrera,scelerisque.dui@hotmail.edu,11,0,1,0,1
20,Dustin Shepard,auctor.velit.aliquam@yahoo.couk,17,1,1,0,1
21,Sylvester Rosa,facilisis.facilisis@outlook.ca,20,1,1,1,1
24,Jocelyn Conley,at.nisi@hotmail.com,19,0,1,0,1
25,Sybill Benson,quis.tristique.ac@protonmail.com,17,1,1,0,1
27,Alan Parks,et.pede@outlook.com,13,0,1,0,0
28,Brock Caldwell,quis.lectus@hotmail.ca,12,1,1,0,1
31,Zenia Farmer,lacus.aliquam@aol.com,37,0,1,0,1
36,Chaney Herrera,scelerisque.dui@hotmail.edu,32,0,1,0,1
40,Dustin Shepard,auctor.velit.aliquam@yahoo.couk,28,1,1,0,1
41,Sylvester Rosa,facilisis.facilisis@outlook.ca,22,1,1,1,1
44,Jocelyn Conley,at.nisi@hotmail.com,20,0,1,0,1
45,Sybill Benson,quis.tristique.ac@protonmail.com,38,1,1,0,1
47,Alan Parks,et.pede@outlook.com,22,0,1,0,0
48,Brock Caldwell,quis.lectus@hotmail.ca,18,1,1,0,1
49,Raja Guerrero,neque.sed@outlook.edu,37,1,1,1,1
50,Gay Keith,orci.ut.sagittis@protonmail.edu,51,1,1,0,1
51,Madonna Riley,aliquam.erat@hotmail.ca,46,1,1,1,0
54,Abra Warren,augue.id@outlook.com,43,0,1,0,1
55,Ciaran Foreman,nec@outlook.edu,47,1,1,0,1
58,Nero Frank,mi.felis@aol.com,51,0,1,0,0
60,Zachary Holland,sit@google.net,47,1,1,0,0
61,Victor Marquez,non.luctus@protonmail.net,39,0,1,0,0
62,Josephine Mcneil,nec.euismod@google.ca,48,1,1,1,1
63,Lisandra Nolan,risus.donec@google.org,43,1,1,0,0
69,Richard Roberson,montes.nascetur@protonmail.org,49,0,1,0,1
71,Prescott Pena,sem.elit@protonmail.net,55,1,1,0,0
74,Celeste Estrada,suspendisse.non@icloud.ca,55,0,1,1,1
76,Amethyst Mcgowan,cubilia.curae@google.org,50,0,1,1,0
79,Sierra Martinez,conubia.nostra@hotmail.edu,54,0,1,0,1
81,Cyrus Swanson,sociis.natoque@aol.couk,80,0,1,0,0
82,Bradley Parks,sapien.cras.dolor@aol.couk,46,0,1,1,0
84,Clinton Hopkins,egestas.fusce@icloud.couk,51,1,1,1,1
85,Christen Rosario,luctus@aol.com,53,1,1,1,1
91,Hoyt Dorsey,eu.erat@aol.ca,50,1,1,1,1
96,Burton Harrison,et.magnis.dis@outlook.ca,84,0,1,0,1
97,Karen Cain,donec@outlook.net,76,0,1,0,1
98,Kathleen Rasmussen,vitae.erat@aol.org,64,1,1,0,0
100,Caleb Osborn,praesent@outlook.net,85,0,1,1,0
101,Garrison Randall,magna.sed.dui@hotmail.ca,57,1,1,1,1
102,Cedric Doyle,vulputate.mauris@protonmail.edu,49,0,1,0,0
105,Cruz Cummings,purus.in.molestie@icloud.edu,67,0,1,1,0
106,Scarlet Medina,est.mauris@google.edu,57,0,1,0,0
108,Deborah Lawrence,a.facilisis.non@hotmail.ca,75,0,1,0,1
111,Rhea Washington,penatibus@hotmail.org,38,0,1,0,1
112,Kerry Hood,egestas@outlook.org,30,1,1,1,1
114,Macy Owens,fermentum@protonmail.com,33,1,1,0,1
115,Leandra Levy,arcu.et@outlook.ca,38,1,1,1,1
118,Kasper Maddox,vel.convallis@google.com,38,0,1,0,0
119,Honorato Whitaker,diam.dictum.sapien@protonmail.edu,30,0,1,1,1
124,Raphael Greer,sit@outlook.couk,39,0,1,0,1

In [52]:
hulu=users[users['Hulu']==1]
hulu

,Nom,email,age,Netflix,Prime,Hulu,Disney+
0,Todd Bates,mollis.lectus.pede@outlook.edu,5,0,0,1,0
3,Christopher Wade,sem.egestas@icloud.org,6,1,0,1,0
6,Jade Pope,dictum.placerat@google.net,7,0,1,1,0
8,Ishmael Merrill,arcu.aliquam@hotmail.ca,4,0,1,1,0
9,Yoshi Bradley,etiam.laoreet@aol.ca,15,0,0,1,1
10,Violet Farrell,donec.fringilla.donec@google.com,11,1,0,1,0
12,Aurora Finch,aliquam.adipiscing@google.edu,17,1,0,1,1
17,Echo Gordon,faucibus.leo@google.net,14,0,0,1,1
18,Rhea Stanton,aliquam.adipiscing@protonmail.ca,12,1,0,1,1
21,Sylvester Rosa,facilisis.facilisis@outlook.ca,20,1,1,1,1
22,Renee Pierce,proin.sed@hotmail.org,14,1,0,1,0
23,Jakeem Welch,sed.turpis@google.com,14,0,0,1,0
26,Luke Peters,ultricies.ligula@aol.ca,17,0,0,1,1
29,Yoshi Bradley,etiam.laoreet@aol.ca,30,0,0,1,1
30,Violet Farrell,donec.fringilla.donec@google.com,27,1,0,1,0
32,Aurora Finch,aliquam.adipiscing@google.edu,27,1,0,1,1
37,Echo Gordon,faucibus.leo@google.net,23,0,0,1,1
38,Rhea Stanton,aliquam.adipiscing@protonmail.ca,25,1,0,1,1
41,Sylvester Rosa,facilisis.facilisis@outlook.ca,22,1,1,1,1
42,Renee Pierce,proin.sed@hotmail.org,31,1,0,1,0
43,Jakeem Welch,sed.turpis@google.com,25,0,0,1,0
46,Luke Peters,ultricies.ligula@aol.ca,28,0,0,1,1
49,Raja Guerrero,neque.sed@outlook.edu,37,1,1,1,1
51,Madonna Riley,aliquam.erat@hotmail.ca,46,1,1,1,0
53,Rinah Mayo,ante@protonmail.net,42,1,0,1,0
56,Clare Harding,erat.neque.non@protonmail.org,43,0,0,1,0
59,Hadley Shannon,lacus.cras@icloud.com,44,0,0,1,0
62,Josephine Mcneil,nec.euismod@google.ca,48,1,1,1,1
66,Axel Brady,curabitur.egestas@google.org,54,0,0,1,0
67,Carissa Love,velit.aliquam@hotmail.com,44,0,0,1,1
68,Darryl Warner,non.feugiat@icloud.com,45,1,0,1,0
72,Eliana Nunez,aliquam@google.ca,66,0,0,1,1
74,Celeste Estrada,suspendisse.non@icloud.ca,55,0,1,1,1
75,Macey Sheppard,nisi.cum@hotmail.com,50,0,0,1,1
76,Amethyst Mcgowan,cubilia.curae@google.org,50,0,1,1,0
82,Bradley Parks,sapien.cras.dolor@aol.couk,46,0,1,1,0
84,Clinton Hopkins,egestas.fusce@icloud.couk,51,1,1,1,1
85,Christen Rosario,luctus@aol.com,53,1,1,1,1
86,Bernard Cameron,neque.in@protonmail.org,67,0,0,1,1
87,Tanek Hawkins,nunc.sed@hotmail.ca,56,0,0,1,1
90,Lamar Stein,ac.facilisis.facilisis@protonmail.couk,53,1,0,1,0
91,Hoyt Dorsey,eu.erat@aol.ca,50,1,1,1,1
93,Ali Reed,fusce.aliquet@google.ca,81,1,0,1,0
100,Caleb Osborn,praesent@outlook.net,85,0,1,1,0
101,Garrison Randall,magna.sed.dui@hotmail.ca,57,1,1,1,1
103,Dominique Sanford,lectus.nullam@google.net,80,0,0,1,0
105,Cruz Cummings,purus.in.molestie@icloud.edu,67,0,1,1,0
110,Mia Sykes,nascetur.ridiculus@protonmail.com,39,1,0,1,1
112,Kerry Hood,egestas@outlook.org,30,1,1,1,1
115,Leandra Levy,arcu.et@outlook.ca,38,1,1,1,1
119,Honorato Whitaker,diam.dictum.sapien@protonmail.edu,30,0,1,1,1
121,MacKenzie Jenkins,convallis.in@protonmail.couk,35,1,0,1,1
123,Doris Hunter,pharetra.nam@outlook.net,36,0,0,1,0
125,Kameko Mccormick,ante.maecenas@aol.ca,37,1,0,1,0
126,Courtney Nelson,malesuada.id@yahoo.com,32,1,0,1,0
127,Mira Michael,nisi.cum@outlook.edu,35,1,0,1,1

In [53]:
disney=users[users['Disney+']==1]
disney

,Nom,email,age,Netflix,Prime,Hulu,Disney+
1,Mohammad Riggs,nullam@aol.couk,5,1,1,0,1
4,Chloe Snyder,pellentesque@protonmail.couk,3,0,0,0,1
5,Wynter Nelson,tellus.sem@protonmail.edu,5,1,0,0,1
7,Uta Moses,nullam.feugiat@yahoo.edu,3,1,1,0,1
9,Yoshi Bradley,etiam.laoreet@aol.ca,15,0,0,1,1
...,...,...,...,...,...,...,...
119,Honorato Whitaker,diam.dictum.sapien@protonmail.edu,30,0,1,1,1
121,MacKenzie Jenkins,convallis.in@protonmail.couk,35,1,0,1,1
124,Raphael Greer,sit@outlook.couk,39,0,1,0,1
127,Mira Michael,nisi.cum@outlook.edu,35,1,0,1,1
128,Jeremy Fulton,quisque@hotmail.com,36,1,0,0,1

<div class="alert alert-success" style="border-left: 5px solid #3c763d;border-radius:2px;">Quel est le nombre d'abonnés de chaque plateforme?</div>

In [55]:
netflix.shape

(59, 7)

In [62]:
prime.shape

(57, 7)

In [57]:
hulu.shape

(56, 7)

In [58]:
disney.shape

(73, 7)

<div class="alert alert-success" style="border-left:5px solid #3c763d;border-radius:2px;">Calculer la moyenne :
    <code>DataFrame['colonne désirée'].mean()</code>
Caluler la moyenne d'age des abonnés de chaque plateforme.</div>

In [63]:
print(netflix['age'].mean())
print(prime['age'].mean())
print(hulu['age'].mean())
print(disney['age'].mean())

35.88135593220339
38.91228070175438
37.07142857142857
34.602739726027394

<div class="alert alert-success" style="border-left: 5px solid #3c763d;border-radius:2px;">Calculer le taux d'abonnements netflix (moyenne de la colonne Netflix).</div>

In [64]:
print(users['Netflix'].mean())

0.4573643410852713

<div class="alert alert-success" style="border-left: 5px solid #3c763d;border-radius:2px;">Calculer le taux d'abonnements à Disney+ par tranche d'âge ( de 0 à 10 ans, de 11 à 20 ans, ...)
Il faudra peut etre envisager de créer des nouveaux sous-dataframe...</div>

In [70]:
age1=users[users['age']<=10]
age2=users[(users['age']<=20)&(users['age']>10)]
age3=users[(users['age']<=30)&(users['age']>20)]
age4=users[(users['age']<=40)&(users['age']>30)]
age5=users[(users['age']<=50)&(users['age']>40)]
age6=users[(users['age']<=60)&(users['age']>50)]
age7=users[(users['age']<=70)&(users['age']>60)]
age8=users[(users['age']<=80)&(users['age']>70)]
age9=users[(users['age']<=90)&(users['age']>80)]

print(age1['Disney+'].mean())
print(age2['Disney+'].mean())
print(age3['Disney+'].mean())
print(age4['Disney+'].mean())
print(age5['Disney+'].mean())
print(age6['Disney+'].mean())
print(age7['Disney+'].mean())
print(age8['Disney+'].mean())
print(age9['Disney+'].mean())

0.4444444444444444
0.7391304347826086
0.7333333333333333
0.64
0.47368421052631576
0.4782608695652174
0.2857142857142857
0.4
0.3333333333333333